### ISSUE TITLE
Error:Execution failed for task ':dexDebug'. > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_101\bin\java.exe'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by Numerah** [KinveyApps/GeoTag-Android#2]
i am getting this error after buliding gradle.

**Comment by Numerah** [comment]
resolved it by adding  "multiDexEnabled true" in gradle.bulid

**Comment by hungdev** [comment]
read more: https://github.com/infinitered/ignite
Problem:

After running react-native android you get the following error:

   com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException:
   Process 'command '     /usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2
Solution:

   cd android
   ./gradlew clean
